### PR TITLE
fix(title): remove default alignment and position

### LINKED ISSUE #322: `title_alignment` does not work as expected
## Description

`title_alignment` does not have effect on `Block` title when used without `Title`.

## To Reproduce

```rs
fn ui<B: Backend>(f: &mut Frame<B>) {
    let size = f.size();

    let block = Block::default()
        .borders(Borders::ALL)
        .title("this should be on center")
        .title_alignment(Alignment::Center);

    f.render_widget(block, size);
}
```

```
┌this should be on center────────────────────────────────┐
│                                                        │
│                                                        │
│                                                        │
│                                                        │
│                                                        │
│                                                        │
└────────────────────────────────────────────────────────┘

```

## Expected behavior

```
┌────────────────this should be on center────────────────┐
│                                                        │
│                                                        │
│                                                        │
│                                                        │
│                                                        │
│                                                        │
└────────────────────────────────────────────────────────┘
```

## Environment

- OS: Arch Linux	
- Terminal Emulator: Alacritty
- Font: Ubuntu Mono
- Crate version: git
- Backend: crossterm

## Additional context

This code works:

```rs
fn ui<B: Backend>(f: &mut Frame<B>) {
    let size = f.size();

    let block = Block::default()
        .borders(Borders::ALL)
        .title(Title::from("this should be on center").alignment(Alignment::Center))
        .title_alignment(Alignment::Center);

    f.render_widget(block, size);
}
```

### PR DESCRIPTION
**Pull request by orhun**
fixes #322

we already have defaults in:

https://github.com/tui-rs-revival/ratatui/blob/446efae185a5bb02a9ab6481542d1dc3024b66a9/src/widgets/block.rs#L151-L152

### CODE REVIEW

**Review by joshka — COMMENTED** [review]
Sensible change to me. Can you please write a test for this (in the block unit tests) that covers the bug mentioned in #322

**Comment by orhun** [comment]
Added test cases for both usages of alignment.

File: src/widgets/block.rs [hunk 1]
```diff
@@ -887,4 +887,15 @@ mod tests {
...
+    #[test]
+    fn title_is_aligned_on_center() {
+        assert_eq!(
+            Block::default()
+                .title("test")
+                .title_alignment(Alignment::Center)
+                .titles_alignment,
+            Alignment::Center
+        );
+    }
```
Comment (joshka) [inline src/widgets/block.rs:900]: This test will still succeed if the `.title()` line is removed.
How about the following which tests the functionality rather than just the property:
```suggestion
#[test]
    fn title_alignment() {
        let mut buffer = Buffer::empty(Rect::new(0, 0, 8, 1));
        let tests = vec![
            (Alignment::Left, "test    "),
            (Alignment::Center, "  test  "),
            (Alignment::Right, "    test"),
        ];

        for (alignment, expected) in tests {
            Block::default()
                .title("test")
                .title_alignment(alignment)
                .render(buffer.area, &mut buffer);
            assert_buffer_eq!(buffer, Buffer::with_lines(vec![expected]));
        }
    }

    #[test]
    fn title_alignment_overrides_block_title_alignment() {
        let mut buffer = Buffer::empty(Rect::new(0, 0, 8, 1));
        let tests = vec![
            // (block.title_alignment, title.alignment, expected)
            (Alignment::Right, Alignment::Left, "test    "),
            (Alignment::Left, Alignment::Center, "  test  "),
            (Alignment::Center, Alignment::Right, "    test"),
        ];

        for (block_title_alignment, alignment, expected) in tests {
            Block::default()
                .title(Title::clone_from("test").alignment(alignment))
                .title_alignment(block_title_alignment)
                .render(buffer.area, &mut buffer);
            assert_buffer_eq!(buffer, Buffer::with_lines(vec![expected]));
        }
    }
```
Incidentally this highlights a bug that the title part doesn't fully erase the background behind the title.:
```text
expected: Buffer {
    area: Rect { x: 0, y: 0, width: 8, height: 1 },
    content: [
        "  test  ",
    ],
    styles: [
        x: 0, y: 0, fg: Reset, bg: Reset, underline: Reset, modifier: NONE,
    ]
}
actual: Buffer {
    area: Rect { x: 0, y: 0, width: 8, height: 1 },
    content: [
        "tetest  ",
    ],
    styles: [
        x: 0, y: 0, fg: Reset, bg: Reset, underline: Reset, modifier: NONE,
    ]
}
```

Comment (orhun) [reply src/widgets/block.rs:900]: Fair point.

**Review by joshka — APPROVED** [review]
